pipelines:
  gocd-example-pipeline-test:
    group: gocd-example-pipeline
    label_template: "${git[:8]}"
    locking: "on"
    timer:
      spec: "* * * * * ? *"
      only_on_changes: yes
    materials:
      git:
        git: https://github.com/leprechaun/gocd-example-pipeline.git
        branch: master
        auto_update: true
        shallow_clone: true
    stages:
      - test-one:
          tasks:
            - exec:
                command: echo
                arguments:
                  - "hello world"

  gocd-example-pipeline-build:
    group: gocd-example-pipeline
    label_template: "${test}"
    locking: "on"
    materials:
      test:
        pipeline: gocd-example-pipeline-test
        stage: test-one
    stages:
      - build:
          tasks:
            - exec:
                command: echo
                arguments:
                  - hello world
            - exec:
                command: kubectl
                arguments:
                  - get
                  - pods
                  - --all-namespaces
            - exec:
                command: docker
                arguments:
                  - ps
            - exec:
                command: docker
                arguments:
                  - build
                  - -t
                  - registry.k8s.fscker.org:80/leprechaun/bs-test-image
                  - .
            - exec:
                command: docker
                arguments:
                  - push
                  - registry.k8s.fscker.org:80/leprechaun/bs-test-image
